<table class="srbacDataGrid" align="center">
	<tr>
		<th width="50%"><?php echo Yii::t('srbac', 'Auth items');?></th>
		<th><?php echo Yii::t('srbac', 'Actions')?></th>
	</tr>
	<tr>
		<td style="vertical-align: top; text-align: center">
			<?php
				$this->widget(
					'system.web.widgets.CTabView',
					array(
						'tabs' => array(
								'automatic_generated' => array(
										'title' => Yii::t('srbac', 'Generated'),
										'view' => 'partials/_authItemGrid',
										'data' => array(
												'model' => $generatedGridModel,
												'gridId' => 'autoGeneratedAuthItem-grid',
												'formId' => 'autoGeneratedAuthItem-form'
										)
								),
								'automatic_suggested' => array(
										'title' => Yii::t('srbac', 'Suggested'),
										'view' => 'partials/_authItemGrid',
										'data' => array(
												'model' => $suggestedGridModel,
												'dataProvider' => $dataProvider,
												'gridId' => 'autoSuggestedAuthItem-grid',
												'formId' => 'autoSuggestedAuthItem-form'
										)
								),
								'automatic_obsolete' => array(
										'title' => Yii::t('srbac', 'Obsolete'),
										'view' => 'partials/_authItemGrid',
										'data' => array(
												'model' => $obsoleteGridModel,
												'gridId' => 'autoObsoleteAuthItem-grid',
												'formId' => 'autoObsoleteAuthItem-form'
										)
								),
						),
						'cssFile' => $this->getModule()->getStylesUrl('srbac.css'),
					)
				);
			?>
		</td>
		<td style="vertical-align: top; text-align: center">
			<?php $this->renderPartial('partials/_authItemForm', array('model' => $formModel, 'gridId' => 'automaticAuthItem-grid', 'formId' => 'automaticAuthItem-form')); ?>
		</td>
	</tr>
</table>
