<div class="iconBox">
	<?php
	echo CHtml::ajaxLink(
			CHtml::image(
						$this->getModule()->getIconsUrl('create.png'),
						Yii::t('srbac', 'Create All'),
						array(
								'border' => 0,
								'class' => 'icon',
								'title' => Yii::t('srbac', 'Create All'),
						)
			) . Yii::t('srbac', 'Create All'),
			$this->createUrl('/srbac/manage/authItem', array('ajax' => 'autoMissingTab')),
			array(
				'type' => 'POST',
				'data' => array('AuthItems' => $dataProvider->rawData),
				'beforeSend' => 'function(){$("#autoMissingTab").addClass("srbacLoading");}',
				'complete' =>
					'function(){'.
						'$("#automaticAuthItem-form").css("display", "none");'.
						'$("#autoMissingTab").removeClass("srbacLoading");'.
						'$("#autoGeneratedAuthItem-grid").yiiGridView("update");'.
					'}',
				'update' => '#autoMissingTab'
			),
			array(
				'title' => Yii::t('srbac', 'Create All')
			)
	);
	?>
</div>
<br /><br />
<?php
$this->renderPartial(
	'partials/_authItemGrid',
	array(
		'model' => $model,
		'dataProvider' => $dataProvider,
		'gridId' => 'autoMissingAuthItem-grid',
		'formId' => 'automaticAuthItem-form'
	)
);
?>
