<?php
$this->breadcrumbs = array(
		Yii::t('srbac', 'RBAC Item Management')
);
if(Yii::app()->getUser()->hasFlash($this->getModule()->flashKey)):
?>
<div id="srbacError">
	<?php
	echo Yii::app()->getUser()->getFlash($this->getModule()->flashKey);
	echo Yii::app()->getUser()->setFlash($this->getModule()->flashKey, null);
	?>
</div>
<?php endif; ?>
<h1><?php Yii::t('srbac', 'Srbac Administration Web Interface'); ?></h1>
<div>
<?php $this->renderPartial('../frontpage'); ?>
	<div class="horTab">
	<?php
		$this->widget(
			'system.web.widgets.CTabView',
			array(
				'tabs' => array(
						'automatic' => array(
								'title' => Yii::t('srbac', 'Automatic'),
								'view' => 'partials/tabs/_automatic',
								'data' => array(
										'generatedGridModel' => $autoGeneratedGridModel,
										'missingGridModel' => $autoMissingGridModel,
										'obsoleteGridModel' => $autoObsoleteGridModel,
										'formModel' => $automaticFormModel,
										'dataProvider' => $dataProvider,
								)
						),
						'manual' => array(
								'title' => Yii::t('srbac', 'Manual'),
								'view' => 'partials/tabs/_manual',
								'data' => array(
										'gridModel' => $manualGridModel,
										'formModel' => $manualFormModel
								)
						),
				),
				'cssFile' => $this->getModule()->getStylesUrl('srbac.css'),
			)
		);
	?>
	</div>
</div>
