<?php
$this->breadcrumbs = array(
		Yii::t('srbac', 'RBAC Item Management')
);
if(Yii::app()->getUser()->hasFlash($this->getModule()->flashKey))
{
?>
<div id="srbacError">
	<?php
	echo Yii::app()->getUser()->getFlash($this->getModule()->flashKey);
	echo Yii::app()->getUser()->setFlash($this->getModule()->flashKey, null);
	?>
</div>
<?php
}

if($this->getModule()->getShowHeader())
{
	$this->renderPartial($this->getModule()->header);
}

?>
<div>
<?php $this->renderPartial('../frontpage'); ?>
	<div class="horTab">
	<?php
		$this->widget(
			'system.web.widgets.CTabView',
			array(
				'tabs' => array(
						'generated' => array(
								'title' => Yii::t('srbac', 'Automatic'),
								'view' => 'partials/tabs/_automatic',
								'data' => array(
										'generatedGridModel' => $autoGeneratedGridModel,
										'suggestedGridModel' => $autoSuggestedGridModel,
										'obsoleteGridModel' => $autoObsoleteGridModel,
										'formModel' => $automaticFormModel,
										'dataProvider' => $dataProvider,
								)
						),
						'custom' => array(
								'title' => Yii::t('srbac', 'Manual'),
								'view' => 'partials/tabs/_manual',
								'data' => array(
										'gridModel' => $manualGridModel,
										'formModel' => $manualFormModel
								)
						),
				),
				'cssFile' => $this->getModule()->getStylesUrl('srbac.css'),
			)
		);
	?>
	</div>
</div>
<?php
if($this->getModule()->getShowFooter())
{
	$this->renderPartial($this->getModule()->footer);
}
?>
