<table class="srbac" align="center">
	<tr>
		<th width="50%"><?php echo SrbacModule::t('Authorization items');?></th>
		<th><?php echo SrbacModule::t('Actions')?></th>
	</tr>
	<tr>
		<td style="vertical-align: top; text-align: center">
			<?php
				$this->widget(
					'system.web.widgets.CTabView',
					array(
						'tabs' => array(
								'autoMissingTab' => array(
										'title' => SrbacModule::t('Missing'),
										'view' => 'partials/tabs/_missing',
										'data' => array(
												'model' => $missingGridModel,
												'dataProvider' => $dataProvider,
										)
								),
								'autoGeneratedTab' => array(
										'title' => SrbacModule::t('Generated'),
										'view' => 'partials/_authItemGrid',
										'data' => array(
												'model' => $generatedGridModel,
												'gridId' => 'autoGeneratedAuthItem-grid',
												'formId' => 'automaticAuthItem-form',
												'deleteSuccessJS' => '$("#autoMissingTab").trigger("update");$("#autoObsoleteTab").trigger("update");'
										)
								),
								'autoObsoleteTab' => array(
										'title' => SrbacModule::t('Obsolete'),
										'view' => 'partials/tabs/_obsolete',
										'data' => array(
												'model' => $obsoleteGridModel,
												'ids' => $obsoleteIds
										)
								),
						),
						'cssFile' => $this->getModule()->getStylesUrl('srbac.css'),
					)
				);
			?>
		</td>
		<td style="vertical-align: top; text-align: center">
			<?php $this->renderPartial('partials/_authItemForm', array('model' => $formModel, 'updateGridIds' => array('autoGeneratedAuthItem-grid', 'autoMissingAuthItem-grid', 'autoObsoleteAuthItem-grid'), 'formId' => 'automaticAuthItem-form')); ?>
		</td>
	</tr>
</table>
