<?php
Yii::app()->getClientScript()->registerScript(
	'automaticMissingTabUpdateEvent',
	'$("#autoMissingTab").bind("update", function(){'.
	CHtml::ajax(array(
			'type' => 'GET',
			'data' => 'ajax=autoMissingTab',
			'beforeSend' => 'function(){$("#autoMissingTab").addClass("srbacLoading");}',
			'complete' => 'function(){$("#autoMissingTab").removeClass("srbacLoading");}',
			'update' => '#autoMissingTab'
		)
	)
	.'})',
	CClientScript::POS_READY
);
?>
<div class="iconBox">
<script type="text/javascript">
var autoMissingAuthItems = <?php echo CJavaScript::encode(array('AuthItems' => $dataProvider->rawData)); ?>;
</script>
	<?php
	echo CHtml::ajaxLink(
			CHtml::image(
						$this->getModule()->getIconsUrl('create.png'),
						Yii::t('srbac', 'Create All'),
						array(
								'border' => 0,
								'class' => 'icon',
								'title' => Yii::t('srbac', 'Create All'),
						)
			) . Yii::t('srbac', 'Create All'),
			$this->createUrl('/srbac/authItem/authItem', array('ajax' => 'autoMissingTab')),
			array(
				'type' => 'POST',
				'data' => 'js:autoMissingAuthItems',
				'beforeSend' => 'function(){$("#autoMissingTab").addClass("srbacLoading");}',
				'complete' =>
					'function(){'.
						'$("#automaticAuthItem-form").css("display", "none");'.
						'$("#autoMissingTab").removeClass("srbacLoading");'.
						'$("#autoGeneratedAuthItem-grid").yiiGridView("update");'.
					'}',
				'update' => '#autoMissingTab'
			),
			array(
				'title' => Yii::t('srbac', 'Create All')
			)
	);
	?>
</div>
<br /><br />
<?php
$this->renderPartial(
	'partials/_authItemGrid',
	array(
		'model' => $model,
		'dataProvider' => $dataProvider,
		'gridId' => 'autoMissingAuthItem-grid',
		'formId' => 'automaticAuthItem-form'
	)
);
?>
