<?php
Yii::app()->getClientScript()->registerScript(
	'automaticObsoleteTabUpdateEvent',
	'$("#autoObsoleteTab").bind("update", function(){'.
	CHtml::ajax(array(
			'type' => 'GET',
			'data' => 'ajax=autoObsoleteTab',
			'beforeSend' => 'function(){$("#autoObsoleteTab").addClass("srbacLoading");}',
			'complete' => 'function(){$("#autoObsoleteTab").removeClass("srbacLoading");}',
			'update' => '#autoObsoleteTab'
		)
	)
	.'})',
	CClientScript::POS_READY
);
?>
<div class="iconBox">
<script type="text/javascript">
var autoObsoleteAuthItems = <?php echo CJavaScript::encode(array('id' => $ids)); ?>;
</script>
	<?php
	echo CHtml::ajaxLink(
			CHtml::image(
						$this->getModule()->getIconsUrl('create.png'),
						Yii::t('srbac', 'Delete All'),
						array(
								'border' => 0,
								'class' => 'icon',
								'title' => Yii::t('srbac', 'Delete All'),
						)
			) . Yii::t('srbac', 'Delete All'),
			$this->createUrl('/'.SrbacUtilities::SRBAC_MODULE_NAME.'/authItem/authItem', array('ajax' => 'autoObsoleteTab')),
			array(
				'type' => 'DELETE',
				'data' => 'js:autoObsoleteAuthItems',
				'beforeSend' => 'function(){$("#autoObsoleteTab").addClass("srbacLoading");}',
				'complete' =>
					'function(){'.
						'$("#automaticAuthItem-form").css("display", "none");'.
						'$("#autoObsoleteTab").removeClass("srbacLoading");'.
						'$("#autoGeneratedAuthItem-grid").yiiGridView("update");'.
					'}',
				'update' => '#autoObsoleteTab'
			),
			array(
				'title' => Yii::t('srbac', 'Delete All')
			)
	);
	?>
</div>
<br /><br />
<?php
$this->renderPartial(
	'partials/_authItemGrid',
	array(
		'model' => $model->obsolete(),
		'gridId' => 'autoObsoleteAuthItem-grid',
		'formId' => 'automaticAuthItem-form',
		'deleteSuccessJS' => '$("#autoGeneratedAuthItem-grid").yiiGridView("update");'
	)
);
?>
